### ISSUE TITLE
org.apache.flink.runtime.taskexecutor.exceptions.RegistrationTimeoutException: Could not register at the ResourceManager within the specified maximum registration duration PT5M. This indicates a problem with this instance. Terminating now.

### ISSUE THREAD

**Issue by dyrnq** [dyrnq/cdc-vagrant#36]
```bash
rg.apache.flink.runtime.taskexecutor.exceptions.RegistrationTimeoutException: Could not register at the ResourceManager within the specified maximum registration duration PT5M. This indicates a problem with this instance. Terminating now.
        at org.apache.flink.runtime.taskexecutor.TaskExecutor.registrationTimeout(TaskExecutor.java:1693) ~[flink-dist-1.20.0.jar:1.20.0]
        at org.apache.flink.runtime.taskexecutor.TaskExecutor.lambda$startRegistrationTimeout$21(TaskExecutor.java:1678) ~[flink-dist-1.20.0.jar:1.20.0]
        at org.apache.flink.runtime.rpc.pekko.PekkoRpcActor.lambda$handleRunAsync$4(PekkoRpcActor.java:460) ~[flink-rpc-akkabf346a2c-93b9-423c-ae58-28b6ab53c302.jar:1.20.0]
        at org.apache.flink.runtime.concurrent.ClassLoadingUtils.runWithContextClassLoader(ClassLoadingUtils.java:68) ~[flink-dist-1.20.0.jar:1.20.0]
        at org.apache.flink.runtime.rpc.pekko.PekkoRpcActor.handleRunAsync(PekkoRpcActor.java:460) ~[flink-rpc-akkabf346a2c-93b9-423c-ae58-28b6ab53c302.jar:1.20.0]
        at org.apache.flink.runtime.rpc.pekko.PekkoRpcActor.handleRpcMessage(PekkoRpcActor.java:225) ~[flink-rpc-akkabf346a2c-93b9-423c-ae58-28b6ab53c302.jar:1.20.0]
        at org.apache.flink.runtime.rpc.pekko.PekkoRpcActor.handleMessage(PekkoRpcActor.java:174) ~[flink-rpc-akkabf346a2c-93b9-423c-ae58-28b6ab53c302.jar:1.20.0]
        at org.apache.pekko.japi.pf.UnitCaseStatement.apply(CaseStatements.scala:33) [flink-rpc-akkabf346a2c-93b9-423c-ae58-28b6ab53c302.jar:1.20.0]
        at org.apache.pekko.japi.pf.UnitCaseStatement.apply(CaseStatements.scala:29) [flink-rpc-akkabf346a2c-93b9-423c-ae58-28b6ab53c302.jar:1.20.0]
        at scala.PartialFunction.applyOrElse(PartialFunction.scala:127) [flink-rpc-akkabf346a2c-93b9-423c-ae58-28b6ab53c302.jar:1.20.0]
        at scala.PartialFunction.applyOrElse$(PartialFunction.scala:126) [flink-rpc-akkabf346a2c-93b9-423c-ae58-28b6ab53c302.jar:1.20.0]
        at org.apache.pekko.japi.pf.UnitCaseStatement.applyOrElse(CaseStatements.scala:29) [flink-rpc-akkabf346a2c-93b9-423c-ae58-28b6ab53c302.jar:1.20.0]
        at scala.PartialFunction$OrElse.applyOrElse(PartialFunction.scala:175) [flink-rpc-akkabf346a2c-93b9-423c-ae58-28b6ab53c302.jar:1.20.0]
        at scala.PartialFunction$OrElse.applyOrElse(PartialFunction.scala:176) [flink-rpc-akkabf346a2c-93b9-423c-ae58-28b6ab53c302.jar:1.20.0]
        at scala.PartialFunction$OrElse.applyOrElse(PartialFunction.scala:176) [flink-rpc-akkabf346a2c-93b9-423c-ae58-28b6ab53c302.jar:1.20.0]
        at org.apache.pekko.actor.Actor.aroundReceive(Actor.scala:547) [flink-rpc-akkabf346a2c-93b9-423c-ae58-28b6ab53c302.jar:1.20.0]
        at org.apache.pekko.actor.Actor.aroundReceive$(Actor.scala:545) [flink-rpc-akkabf346a2c-93b9-423c-ae58-28b6ab53c302.jar:1.20.0]
        at org.apache.pekko.actor.AbstractActor.aroundReceive(AbstractActor.scala:229) [flink-rpc-akkabf346a2c-93b9-423c-ae58-28b6ab53c302.jar:1.20.0]
        at org.apache.pekko.actor.ActorCell.receiveMessage(ActorCell.scala:590) [flink-rpc-akkabf346a2c-93b9-423c-ae58-28b6ab53c302.jar:1.20.0]
        at org.apache.pekko.actor.ActorCell.invoke(ActorCell.scala:557) [flink-rpc-akkabf346a2c-93b9-423c-ae58-28b6ab53c302.jar:1.20.0]
        at org.apache.pekko.dispatch.Mailbox.processMailbox(Mailbox.scala:280) [flink-rpc-akkabf346a2c-93b9-423c-ae58-28b6ab53c302.jar:1.20.0]
        at org.apache.pekko.dispatch.Mailbox.run(Mailbox.scala:241) [flink-rpc-akkabf346a2c-93b9-423c-ae58-28b6ab53c302.jar:1.20.0]
        at org.apache.pekko.dispatch.Mailbox.exec(Mailbox.scala:253) [flink-rpc-akkabf346a2c-93b9-423c-ae58-28b6ab53c302.jar:1.20.0]
        at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290) [?:?]
        at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020) [?:?]
        at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656) [?:?]
        at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594) [?:?]
        at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183) [?:?]
2024-11-13 16:13:04,481 ERROR org.apache.flink.runtime.taskexecutor.TaskManagerRunner      [] - Fatal error occurred while executing the TaskManager. Shutting it down...
org.apache.flink.runtime.taskexecutor.exceptions.RegistrationTimeoutException: Could not register at the ResourceManager within the specified maximum registration duration PT5M. This indicates a problem with this instance. Terminating now.
        at org.apache.flink.runtime.taskexecutor.TaskExecutor.registrationTimeout(TaskExecutor.java:1693) ~[flink-dist-1.20.0.jar:1.20.0]
        at org.apache.flink.runtime.taskexecutor.TaskExecutor.lambda$startRegistrationTimeout$21(TaskExecutor.java:1678) ~[flink-dist-1.20.0.jar:1.20.0]
        at org.apache.flink.runtime.rpc.pekko.PekkoRpcActor.lambda$handleRunAsync$4(PekkoRpcActor.java:460) ~[flink-rpc-akkabf346a2c-93b9-423c-ae58-28b6ab53c302.jar:1.20.0]
        at org.apache.flink.runtime.concurrent.ClassLoadingUtils.runWithContextClassLoader(ClassLoadingUtils.java:68) ~[flink-dist-1.20.0.jar:1.20.0]
        at org.apache.flink.runtime.rpc.pekko.PekkoRpcActor.handleRunAsync(PekkoRpcActor.java:460) ~[flink-rpc-akkabf346a2c-93b9-423c-ae58-28b6ab53c302.jar:1.20.0]
        at org.apache.flink.runtime.rpc.pekko.PekkoRpcActor.handleRpcMessage(PekkoRpcActor.java:225) ~[flink-rpc-akkabf346a2c-93b9-423c-ae58-28b6ab53c302.jar:1.20.0]
        at org.apache.flink.runtime.rpc.pekko.PekkoRpcActor.handleMessage(PekkoRpcActor.java:174) ~[flink-rpc-akkabf346a2c-93b9-423c-ae58-28b6ab53c302.jar:1.20.0]
        at org.apache.pekko.japi.pf.UnitCaseStatement.apply(CaseStatements.scala:33) [flink-rpc-akkabf346a2c-93b9-423c-ae58-28b6ab53c302.jar:1.20.0]
        at org.apache.pekko.japi.pf.UnitCaseStatement.apply(CaseStatements.scala:29) [flink-rpc-akkabf346a2c-93b9-423c-ae58-28b6ab53c302.jar:1.20.0]
        at scala.PartialFunction.applyOrElse(PartialFunction.scala:127) [flink-rpc-akkabf346a2c-93b9-423c-ae58-28b6ab53c302.jar:1.20.0]
        at scala.PartialFunction.applyOrElse$(PartialFunction.scala:126) [flink-rpc-akkabf346a2c-93b9-423c-ae58-28b6ab53c302.jar:1.20.0]
        at org.apache.pekko.japi.pf.UnitCaseStatement.applyOrElse(CaseStatements.scala:29) [flink-rpc-akkabf346a2c-93b9-423c-ae58-28b6ab53c302.jar:1.20.0]
        at scala.PartialFunction$OrElse.applyOrElse(PartialFunction.scala:175) [flink-rpc-akkabf346a2c-93b9-423c-ae58-28b6ab53c302.jar:1.20.0]
        at scala.PartialFunction$OrElse.applyOrElse(PartialFunction.scala:176) [flink-rpc-akkabf346a2c-93b9-423c-ae58-28b6ab53c302.jar:1.20.0]
        at scala.PartialFunction$OrElse.applyOrElse(PartialFunction.scala:176) [flink-rpc-akkabf346a2c-93b9-423c-ae58-28b6ab53c302.jar:1.20.0]
        at org.apache.pekko.actor.Actor.aroundReceive(Actor.scala:547) [flink-rpc-akkabf346a2c-93b9-423c-ae58-28b6ab53c302.jar:1.20.0]
        at org.apache.pekko.actor.Actor.aroundReceive$(Actor.scala:545) [flink-rpc-akkabf346a2c-93b9-423c-ae58-28b6ab53c302.jar:1.20.0]
        at org.apache.pekko.actor.AbstractActor.aroundReceive(AbstractActor.scala:229) [flink-rpc-akkabf346a2c-93b9-423c-ae58-28b6ab53c302.jar:1.20.0]
        at org.apache.pekko.actor.ActorCell.receiveMessage(ActorCell.scala:590) [flink-rpc-akkabf346a2c-93b9-423c-ae58-28b6ab53c302.jar:1.20.0]
        at org.apache.pekko.actor.ActorCell.invoke(ActorCell.scala:557) [flink-rpc-akkabf346a2c-93b9-423c-ae58-28b6ab53c302.jar:1.20.0]
        at org.apache.pekko.dispatch.Mailbox.processMailbox(Mailbox.scala:280) [flink-rpc-akkabf346a2c-93b9-423c-ae58-28b6ab53c302.jar:1.20.0]
        at org.apache.pekko.dispatch.Mailbox.run(Mailbox.scala:241) [flink-rpc-akkabf346a2c-93b9-423c-ae58-28b6ab53c302.jar:1.20.0]
        at org.apache.pekko.dispatch.Mailbox.exec(Mailbox.scala:253) [flink-rpc-akkabf346a2c-93b9-423c-ae58-28b6ab53c302.jar:1.20.0]
        at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290) [?:?]
        at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020) [?:?]
        at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656) [?:?]
        at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594) [?:?]
        at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183) [?:?]

```

**Comment by dyrnq** [comment]
缺少bucket

```bash
mc mb myminio/flink
mc mb myminio/flink-state
```
